### ISSUE TITLE
Not working with node-webkit

### ISSUE THREAD

**Issue by goldfire** [sockjs/sockjs-client#216]
Testing on node-webkit 0.10.x and 0.11.x, sock.js 1.0 fails to connect. However, reverting to 0.3.4 works perfectly. I've yet to figure out what might be causing this, but thought someone else might have run into this as well.

**Comment by bytekoders** [comment]
Is there any update on the Issue?

**Comment by brycekahle** [comment]
@bytekoders I'm waiting for more information from @goldfire. If you anyinformation, that would be a lot of help. I need way more detail before I can go about confirming the issue.

**Comment by brycekahle** [comment]
Closing due to insufficient information

**Comment by hgwood** [comment]
I'm running into this issue and investigating it. The problem arises because of browserify expecting either `global` or `window` to be defined, but not both like in node-webkit.

For [example](https://github.com/sockjs/sockjs-client/blob/master/lib/transport/browser/websocket.js):

```js
module.exports = global.WebSocket || global.MozWebSocket;
```

In SockJS' browser build, browserify replaces `global` by the expression `typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {}`. In a browser, this expression returns`window`. In node-webkit, `global` is defined and gets picked up, but it does *not* have a property `WebSocket`. Therefore, `"All transports failed"`.

So this is effectively a problem between browserify and node-webkit. See [this issue](https://github.com/substack/node-browserify/issues/481). I'm still looking for the right way to fix, in particular if SockJS can do something about it or if the fix should be on the consumer side.

**Comment by hgwood** [comment]
Workaround: `Object.setPrototypeOf(global, window)`.

**Comment by brycekahle** [comment]
It appears that browserify can fix this without needing SockJS to do anything specific.

**Comment by hgwood** [comment]
Yes, I agree.

**Comment by Slayer95** [comment]
This is fixed for me with the latest ``nw.js 0.13 RC``
