### ISSUE TITLE
Frustration factor about new sockJsOptions increased

### ISSUE THREAD

**Issue by leolux** [sockjs/sockjs-client#259]
The renaming of the option "protocols_whitelist" to "transports" increased my frustration factor because it does not add any value but produces unnecessary effort.

Please don't do that again in the future.

**Comment by brycekahle** [comment]
It was necessary because the terminology was incorrect and would be confusing once subprotocol support was added. Semver was followed to indicate a breaking change. A deprecation warning was also added. Sometimes breaking changes are needed and the version number is used to communicate that. 

In the future, please be constructive with your criticism. I don't get paid to work on this project, and you get it for free. The price of admission is to participate in a civil and meaningful way.

**Comment by leolux** [comment]
Well, the terminology is one thing but the frustration is the other. The need to rename "protocol" to "transport" is not a breaking change in my eyes :-)

**Comment by brycekahle** [comment]
Changing the API is definitely a breaking change.

**Comment by leolux** [comment]
And the semantic of this option is still the same, so I don't care how you want to name this option.

**Comment by 3rd-Eden** [comment]
Well then on earth create this damn issue if you don't care about the damn name of the option.

**Comment by leolux** [comment]
No problem. And you are totally right. I won't complain about my frustration factors in future^^
