### ISSUE TITLE
HEUR:Trojan-Downloader.Script.Generic detected by virus scanner

### ISSUE THREAD

**Issue by Manfred73** [sockjs/sockjs-client#300]
In our project we have a dependency to  webpack-dev-server version 1.9.0, With this version we also get sockjs-client version 1.0.3. 

However, when I now run my project in development mode (npm run dev), it fails to start with the following error:

ERROR in (webpack)-dev-server/~/sockjs-client/lib/transport/htmlfile.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./receiver/htmlfile in c:\Projects\fle
etguard\fleetguard-ui\node_modules\webpack-dev-server\node_modules\sockjs-client\lib\transport
 @ (webpack)-dev-server/~/sockjs-client/lib/transport/htmlfile.js 4:23-53

The htmlfile.js gets deleted by the virusscanner and is removed. Unfortunately I don't have the possibility to ignore this file in the virusscanner (Check Point Endpoint Security). Is there a workaround for this?

**Comment by brycekahle** [comment]
I'm not aware of a workaround, this is the first time this has been reported. This seems really aggressive for the virus scanner though.

**Comment by Manfred73** [comment]
Thanks for your reply. Problem will be solved by whitelisting this file.

**Comment by jon99-au** [comment]
Hi there, I realise this issue is closed, but as we are experiencing it as well I thought I could add a bit more information. This seems to be (also) caused by a incorrect antivirus match, this time in Kaspersky's BlueCoat product, the details are: 

- Virus/PUS: "HEUR:Trojan-Downloader.Script.Generic" found!
- ProxyAV: http://www.BlueCoat.com/
- Antivirus Vendor: Kaspersky Labs
- I believe we are using the latest definitions from Kaspersky

Unfortunately I am not sure why the match is being returned though I would guess it is a heuristic match. The fix for our team won't be as simple, as we do not have the ability to whitelist files. Our temporary fix at the moment has been to downgrade our webpack versions back to 1.12 which does not use sockjs, however this will obviously not work long term .

I am not sure how one would go about getting something removed from this sort of anti-virus block, potentially seeing why there is a heuristic match might help diagnose it. Or perhaps contacting one of the anti-virus companies directly if you know anyone who has a contact.
