### ISSUE TITLE
Transport Timeout doesn't close that connection

### ISSUE THREAD

**Issue by cyr0930** [sockjs/sockjs-client#334]
Sometimes transportTimeout occurs even if connection established successfully.
In this case, sockJS tries to connect with other transport, but previous connection still remains.
Why doesn't sockJS close previous connection?

**Comment by SammyVimes** [comment]
Same here, I see lots of pending xhr-streaming requests and the page just hangs, because of same domain request queue limit.

**Comment by FZambia** [comment]
+1 - I can reliably reproduce infinite reconnect caused by closing stale transport. In case of [Centrifugo](https://github.com/centrifugal/centrifugo) we close stale connections after 25 seconds - when we do this infinite reconnect starts ddosing backend with connection attempts.  Here are some screenshots - I put my backend behind proxy where `xhr-streaming` and `eventsource` time out on connecting so connection falls back to `xhr-polling`.

Here is first step: we see that xhr-streaming timed out and xhr-polling was established but `xhr-streaming` left pending:
<img width="1155" alt="screen shot 2017-02-18 at 21 37 17" src="https://cloud.githubusercontent.com/assets/1196565/23095921/70d68eb4-f623-11e6-8c6e-7d201113e761.png">

Then after 25 seconds Centrifugo closes stale connections:
<img width="1265" alt="screen shot 2017-02-18 at 21 40 32" src="https://cloud.githubusercontent.com/assets/1196565/23095925/8c097d2c-f623-11e6-872a-6c71b762d7ac.png">

And at this moment infinite reconnect starts:
<img width="1277" alt="screen shot 2017-02-18 at 21 40 51" src="https://cloud.githubusercontent.com/assets/1196565/23095929/9dcd1c58-f623-11e6-8cfb-9deb94a4eb30.png">

@brycekahle  fix from #358 resolves this issue as `xhr-streaming` and `eventsource` connections are cancelled properly on timeout:

<img width="1436" alt="screen shot 2017-02-18 at 21 49 18" src="https://cloud.githubusercontent.com/assets/1196565/23095949/24cabb02-f624-11e6-8c0f-1e6a73d003bb.png">

And everything starts working fine.

**Comment by FZambia** [comment]
Continue experimenting with this, looks like fix in #358 can cause this warning in Chrome when closing websocket transport before its `onopen` callback was fired:

<img width="1432" alt="screen shot 2017-02-19 at 21 09 28" src="https://cloud.githubusercontent.com/assets/1196565/23104909/c08f5f8e-f6e7-11e6-80be-6ef9248e68ee.png">

In my artificial setup I just use Nginx without properly set websocket proxy (i.e. only using `proxy_pass` to backend without upgrade so websocket connection fails). This warning happens from time to time.

**Comment by FZambia** [comment]
@brycekahle please could you look at this? In my opinion this is very critical as infinite reconnect is like a bomb that can destroy service at some moment.

**Comment by brycekahle** [comment]
Have you tried `1.1.2`? That should fix it.

**Comment by FZambia** [comment]
@brycekahle yep, I am on 1.1.2, btw I've already written about this in [comment](https://github.com/sockjs/sockjs-client/pull/343#issuecomment-274292316) - _transportClose called from [_transportTimeout](https://github.com/sockjs/sockjs-client/blob/master/lib/main.js#L233) too, not only on close event.

**Comment by zzq0324** [comment]
@FZambia could you please share your nginx's configuration to reproduce  this scenario? I have tried to set proxy_buffering on, buf I can't reproduce it. Thank you

**Comment by FZambia** [comment]
@brycekahle any thoughts? Do you have enough information to understand what's going on here?

**Comment by brycekahle** [comment]
@FZambia I need more detail on the conditions that cause a transport to successfully connect, but not emit the `open` event. If you have debug logs that would be very helpful for me.

**Comment by brycekahle** [comment]
I was mistaken on that scenario you were describing. I believe I understand the issue now. It appears that SockJS is not cleaning up transports that timeout (ensuring XHRs are aborted, timers stopped, etc.). The PR in #358 is a good start, but I need to do some verification that a duplicate `close` event would not be fired.

**Comment by brycekahle** [comment]
@FZambia I believe it is better to sometimes get the warning about closing the WebSocket too early, than to not do it at all. I do not think there is a way to avoid triggering the error at all because it seems to be based on internal state of the WebSocket.

**Comment by FZambia** [comment]
> I believe it is better to sometimes get the warning about closing the WebSocket too early, than to not do it at all

What I am afraid here that maybe in some browsers this won't be a warning but results in unhandled exception that can corrupt application js code execution?

I just tried to simulate a situation where Websocket connection times out (sleep on 1 second in Upgrade code on server) - so xhr-streaming established successfully. Then after 1 second Websocket connection established successfully in background, and after 25 seconds it was cleanly closed by server as inactive. And this does not result in infinite reconnect while in case when xhr-streaming/evensource transports fallback to xhr-polling it does.

**Comment by FZambia** [comment]
Just tried the latest SockJS with merged #358 and simulated websocket timeout - it works fine in all browsers I found at home - latest Chrome, Firefox, Safari, Android builtin browser, Chrome on Android. So I think we can live with this warning as it does not break code and actually should be a rare case in production.

**Comment by eelzter** [comment]
We encouter this problem quite a lot, I see that the fixed is merged into master. Is there a release with it coming up soon?

**Comment by brycekahle** [comment]
@eelzter `1.1.5` has the fix, and was released on 29 May 2018

**Comment by WenderGalan** [comment]
Guys, I'm having the same problem in version v1.5.0, I updated to version v1.6.0 but the problem still occurs, after the browser is minimized for a few minutes, the infinite loop starts and even the application requests crash.
