### ISSUE TITLE
Minified files in dist/ are not working in IE8

### ISSUE THREAD

**Issue by uvinw** [sockjs/sockjs-client#393]
Something in the minification process prevents the file from being parsed properly in Internet Explorer 8. The exact error thrown is `Object expected` which results in `SockJS is undefined`.

Solved the issue by using the full version that was not minified.

**Comment by kichik** [comment]
I was able to resolve this issue by using `<script type="javascript" src="..."></script>` based on a similar [StackOverflow question about prototype.js](https://stackoverflow.com/questions/949431/object-expected-javascript-error-in-ie8-when-using-prototype-js).

**Comment by qq8057656qq** [comment]
same issue....

**Comment by brycekahle** [comment]
@uvinw Is it possible for you to find out which version starts causing this error? You can iterate through versions in the jsdelivr URL `https://cdn.jsdelivr.net/npm/sockjs-client@1.1.5/dist/sockjs.min.js`

I don't have easy access to IE8 at the moment.

**Comment by kichik** [comment]
Microsoft has a [free VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). It's a painfully long debugging process as IE8 JavaScript console is ancient. I'm sorry, but I don't have time to test it now.

**Comment by brycekahle** [comment]
@uvinw @qq8057656qq @kichik If one of you can determine which version introduces the error, I can look into it further. It should be working in IE8 as of 1.1.0, since I fixed https://github.com/sockjs/sockjs-client/pull/279 for IE8 in that release.

I don't have infinite time to chase this down in a browser with 0.22% of global usage. I need your help.

**Comment by sxlvalue** [comment]
same issue
