### ISSUE TITLE
Infinite request loop when server sends status code 200

### ISSUE THREAD

**Issue by anrub** [sockjs/sockjs-client#440]
Through another condition our load-balancer sent code 200 on those sockjs /xhr/../xhr_streaming requests.
sockjs handles this with an extreme infinite loop of requests.

This is dangerous, as it hammers down the whole network, if there are enough open browser windows.

Of course it is wrong to send the 200 response, but the result is so harmful, that a general handling to prevent those fast request loops within sockjs would be really good.

**Comment by voliva** [comment]
I'm having the same problem - I found the source of the infinite loop, but without fully understanding the logic behind this, I'm not sure if it's just safe to throttle down the requests.

It's in here: https://github.com/sockjs/sockjs-client/blob/0ab53b8bf24ead0df4bed488333ceb9e81b8c1b7/lib/transport/lib/polling.js#L23-L39

So Polling.scheduleReciever is getting the poll object emitting 'close', and if the reason is 'network', then it reschedules again.

**Comment by brycekahle** [comment]
Throttling the speed at which these requests happen, would also slow-down connections that are actually sending data at a high-rate, even if only for a short while.
