### ISSUE TITLE
Websocket is supported but it is using xhr

### ISSUE THREAD

**Issue by atilkan** [sockjs/sockjs-client#462]
![screen shot 2018-11-16 at 16 31 05](https://user-images.githubusercontent.com/1254613/48624360-40336180-e9bd-11e8-9f45-d17117f741e6.png)

![screen shot 2018-11-16 at 16 32 32](https://user-images.githubusercontent.com/1254613/48624355-3dd10780-e9bd-11e8-98a8-38d6a6235f87.png)

Also build failing banner doesn't feel great on the repo.

**Comment by brycekahle** [comment]
Browser support isn't the only factor that influences whether websocket is used. If you look at all network requests, you should it attempting to use websocket and failing. One reason for this could be the network between the client and your server.

> Also build failing banner doesn't feel great on the repo.

This is because of CI issues, not because the the library doesn't pass the tests. Everything works great locally.

**Comment by atilkan** [comment]
If connecting to websocket URI is failing then what is it trying to connect with XHR.
