### ISSUE TITLE
Error: Incompatible SockJS! Main site uses: "1.3.0", the iframe: "1.4.0".

### ISSUE THREAD

**Issue by ISchwarz23** [sockjs/sockjs-client#488]
Hello everyone,
currently the following issue occurs in the client when the socket is forwarded by an nginx proxy:

> Incompatible SockJS! Main site uses: "1.3.0", the iframe: "1.4.0".

The issue is not occurring when the socket is directly connected to the service without nginx proxy.
The frontend is written in angular 7 and uses the "vertx3-eventbus-client" library which uses the sockjs client.

Could you please explain why the issue occurs and how to avoid it?

Best regards,
Ingo

**Comment by brycekahle** [comment]
This likely because you have your frontend pinned to `sockjs-client 1.3.0`. When you are using the proxy, the direct transports are probably failing, and it is falling back to `iframe` based transports. In those cases, the server has to load another copy of the client in the `iframe`. It does that using the latest `1.x` version (by default), which is `1.4.0`.

You can either:
1. Upgrade your frontend to `sockjs-client 1.4.0`
OR
2. Explicitly set your server to use `sockjs-client 1.3.0` with the [`sockjs_url` option](https://github.com/sockjs/sockjs-node/tree/v0.3.19#server-class) on the server
